[[blockSQP_mumps]]
arch = "aarch64"
git-tree-sha1 = "54ed2f4603aed3d48352d3007f7b099efe6f605a"
julia_version = "1.10.0"
os = "macos"

    [[blockSQP_mumps.download]]
    sha256 = "b7763b7c9361c2e8b6510ce0c563f73933a2280fd7264ccb55d5fe31d263ab74"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[blockSQP_mumps]]
arch = "aarch64"
git-tree-sha1 = "3c051b4f828d3aacec4f6909e87ebcefe6ec3483"
julia_version = "1.11.1"
os = "macos"

    [[blockSQP_mumps.download]]
    sha256 = "050858064e32b63cb94589f4854e86d8cfd4860369cca52370b97c55618e80b5"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.aarch64-apple-darwin-julia_version+1.11.1.tar.gz"
[[blockSQP_mumps]]
arch = "aarch64"
git-tree-sha1 = "400f379a117a15956abd76f5a3914efd1241a0b7"
julia_version = "1.12.0"
os = "macos"

    [[blockSQP_mumps.download]]
    sha256 = "9cebbf53fb852c109c17f638cb3ac5107633f663f10318272f9f2b4535abc4f2"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.aarch64-apple-darwin-julia_version+1.12.0.tar.gz"
[[blockSQP_mumps]]
arch = "aarch64"
git-tree-sha1 = "20b89e94dc72e07ddf0049f41acd0be59eb15dcd"
julia_version = "1.13.0"
os = "macos"

    [[blockSQP_mumps.download]]
    sha256 = "636735fc5ec2f2220225c0030c8df91a6dcd936cbc40c48e82a643127e051f4f"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.aarch64-apple-darwin-julia_version+1.13.0.tar.gz"
[[blockSQP_mumps]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d5a9269d50d0526b7c5cf1d3cd06fa587fbe95e"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[blockSQP_mumps.download]]
    sha256 = "581819484c7d07a8bcde0d2a650753936302816f33538ef53c0d27d1f54217e7"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.aarch64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[blockSQP_mumps]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc92946f0eb947c2914ba4137ef236ee872639c5"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[blockSQP_mumps.download]]
    sha256 = "defe91e5aca0449f9e474733505967173e57036bd3534e9016dd86a675a5b6af"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.aarch64-linux-gnu-cxx03-julia_version+1.11.1.tar.gz"
[[blockSQP_mumps]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87405e10c1a282191159d20fb1c28f398db75444"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[blockSQP_mumps.download]]
    sha256 = "e2d4a30cccb8e2b0d804b910c03c311ae631ccbc5702fb23c9b871aee5b3f724"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.aarch64-linux-gnu-cxx03-julia_version+1.12.0.tar.gz"
[[blockSQP_mumps]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b2c635d1e65ad46ccdd794ec79482f3a2313e749"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[blockSQP_mumps.download]]
    sha256 = "74d5c67f92055e6242ff911d504e328d93c38ca4d147876b5f768f323772ed73"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.aarch64-linux-gnu-cxx03-julia_version+1.13.0.tar.gz"
[[blockSQP_mumps]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "578d63ca33f3539310531c28548534099c6aa062"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[blockSQP_mumps.download]]
    sha256 = "0ec976397a623ebf5bd6b95ebbd38bf93645c4fe8e442e2bc1533ef7200e1044"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[blockSQP_mumps]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05cd9f5f1201a321efcb95c3863b0af7881b0555"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[blockSQP_mumps.download]]
    sha256 = "25c2e0b52bc715b01be25111a728d6c314fb4e636585f418c4634bcfe9a05bd3"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.aarch64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[blockSQP_mumps]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12c8decc598fc6d33512a3f69bebab6414cb13bb"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[blockSQP_mumps.download]]
    sha256 = "95c7a71a61db40fb7fc1980220a1d16d0fb23524ca3a4f54904dbfbafca1b04b"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.aarch64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[blockSQP_mumps]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3232d35105ced27bc765b20e6118e8998ecf0803"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[blockSQP_mumps.download]]
    sha256 = "b26215aebff08d8ef61815c7656987fbd407154c2e0d1b617d3d7ba8f1cc3533"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.aarch64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[blockSQP_mumps]]
arch = "x86_64"
git-tree-sha1 = "cdf9044e49008ee819d27259f04aff5fd127332e"
julia_version = "1.10.0"
os = "macos"

    [[blockSQP_mumps.download]]
    sha256 = "ce3da4cf86dcab825d117d3f6cbfa95ff01d3a86f1b410a56e7f4a0e4f45c05d"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[blockSQP_mumps]]
arch = "x86_64"
git-tree-sha1 = "f847c8b166262a3eb539b0a6456b0dbdb96de068"
julia_version = "1.11.1"
os = "macos"

    [[blockSQP_mumps.download]]
    sha256 = "5d7efd3d149f82ee9f4b415392c33eda87140bb717c40c84a0bbd7c13d2d2278"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.x86_64-apple-darwin-julia_version+1.11.1.tar.gz"
[[blockSQP_mumps]]
arch = "x86_64"
git-tree-sha1 = "77b238a9cb475beed2de9a3dd1a7344443560a1e"
julia_version = "1.12.0"
os = "macos"

    [[blockSQP_mumps.download]]
    sha256 = "be4d164974924951e3ea364919cb39c30a597d45f79961227497be22164127cd"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.x86_64-apple-darwin-julia_version+1.12.0.tar.gz"
[[blockSQP_mumps]]
arch = "x86_64"
git-tree-sha1 = "a368cb7589fdede47251c276e4bffc38d21b4aa2"
julia_version = "1.13.0"
os = "macos"

    [[blockSQP_mumps.download]]
    sha256 = "50a4e1343367d86c4703f55c5c7d9e0165ecd49009a63990c86c9ad968734580"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.x86_64-apple-darwin-julia_version+1.13.0.tar.gz"
[[blockSQP_mumps]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c1388d351ace643e1551cef5a5c4ba358abf616c"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[blockSQP_mumps.download]]
    sha256 = "2d7480f97e4fef9e707269f01866a6758c2a8cf3cd858e9bf7fd801da07969b9"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.x86_64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[blockSQP_mumps]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f368f8772dfe5e0a5beac2c33d090c97bf949e7"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[blockSQP_mumps.download]]
    sha256 = "a99de061191b9b98576dda7ae8656f4d6baa88039df43a023f5d6d25d76b67f4"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.x86_64-linux-gnu-cxx03-julia_version+1.11.1.tar.gz"
[[blockSQP_mumps]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b7d639212582afdfcfbbc6f2092b917c0d2e56a2"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[blockSQP_mumps.download]]
    sha256 = "27156ff3a6e4b0ff48686e2e6e1994fc740da4d125401244d34f43d181fcc776"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.x86_64-linux-gnu-cxx03-julia_version+1.12.0.tar.gz"
[[blockSQP_mumps]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cdc464d394bba5a3b0d39d48cab3d55fd03c6eed"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[blockSQP_mumps.download]]
    sha256 = "543ad83624d8e0484d79b07eab6f0fcf85661cdc1ad11d90e28b6f84b56b4b97"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.x86_64-linux-gnu-cxx03-julia_version+1.13.0.tar.gz"
[[blockSQP_mumps]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5331335ae88408ab2aff83b1bb3d82d5cbf64cf3"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[blockSQP_mumps.download]]
    sha256 = "73089273e7717fe5028ead573054cf8629dfe469cc470cf5bccfd89e16358347"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[blockSQP_mumps]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c18684b6d4cc3208977043f3da1a70e5e2c1f0c6"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[blockSQP_mumps.download]]
    sha256 = "ea7a7a0249a0337714354a45ad97798fc1eeadd17eddee2e3bd5be576f481c11"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.x86_64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[blockSQP_mumps]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24a53196eaa6ca385864bc98da39e594f5c27315"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[blockSQP_mumps.download]]
    sha256 = "33332ea3bd1515b37834b6c80229f10558224748f605e234a0368e3bed0957e3"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[blockSQP_mumps]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "92c3838dcc753f75fbe7321a48a82f5390af6bdd"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[blockSQP_mumps.download]]
    sha256 = "68bd9124fc77383c36bfd9429b388272356ae3972264d443dc2c63e5276d33a6"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.x86_64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[blockSQP_mumps]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15ca3e182b2c30e2c4a2ddff593786c3c5b734a4"
julia_version = "1.10.0"
os = "windows"

    [[blockSQP_mumps.download]]
    sha256 = "0bbfe8296956d32dc4ab99a8559145256a90d4e4976f232ed529b022d1bf9b95"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.x86_64-w64-mingw32-cxx03-julia_version+1.10.0.tar.gz"
[[blockSQP_mumps]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fc80b0e6d2ab527e2eaa768eb1718e7e5b04283e"
julia_version = "1.11.1"
os = "windows"

    [[blockSQP_mumps.download]]
    sha256 = "5780cefbd2ea8bd0edf0d01d5c0605de2febe448678c98330a4c482a66d2903e"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.x86_64-w64-mingw32-cxx03-julia_version+1.11.1.tar.gz"
[[blockSQP_mumps]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6d71e24ee6f20890474aee69b79169c6eb6af57"
julia_version = "1.12.0"
os = "windows"

    [[blockSQP_mumps.download]]
    sha256 = "96f392c1eb8e6a4fb2d8f58460f1606fe922d2cce7111bdebbb01cceee9fd885"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.x86_64-w64-mingw32-cxx03-julia_version+1.12.0.tar.gz"
[[blockSQP_mumps]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6d71e24ee6f20890474aee69b79169c6eb6af57"
julia_version = "1.13.0"
os = "windows"

    [[blockSQP_mumps.download]]
    sha256 = "96f392c1eb8e6a4fb2d8f58460f1606fe922d2cce7111bdebbb01cceee9fd885"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.x86_64-w64-mingw32-cxx03-julia_version+1.13.0.tar.gz"
[[blockSQP_mumps]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68af47d7103fc4d2924df96cd452d67ad42e20a6"
julia_version = "1.10.0"
os = "windows"

    [[blockSQP_mumps.download]]
    sha256 = "b6aede488ff5c9144d53cdcab43ee26637982c58bad80c94a5f413e93f2857ea"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[blockSQP_mumps]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aab8260d5c7bdab6263710a79808446777b49128"
julia_version = "1.11.1"
os = "windows"

    [[blockSQP_mumps.download]]
    sha256 = "5fba6b43451b77667b474678c0a26dc51b85c62de8fe2f525f0ab3504d4a6868"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.x86_64-w64-mingw32-cxx11-julia_version+1.11.1.tar.gz"
[[blockSQP_mumps]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "adc6b9b414ee78268e4e8e8e8de46726ba8783ce"
julia_version = "1.12.0"
os = "windows"

    [[blockSQP_mumps.download]]
    sha256 = "f9ad3f5fb25835bcb99e8c9a08137fe7baacebf4e963bc6a2c5ad5bb4bc0c5ef"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.x86_64-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
[[blockSQP_mumps]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "adc6b9b414ee78268e4e8e8e8de46726ba8783ce"
julia_version = "1.13.0"
os = "windows"

    [[blockSQP_mumps.download]]
    sha256 = "f9ad3f5fb25835bcb99e8c9a08137fe7baacebf4e963bc6a2c5ad5bb4bc0c5ef"
    url = "https://github.com/chplate/blockSQP_mumps/releases/download/blockSQP_mumps-v0.0.1+0/blockSQP_mumps.v0.0.1.x86_64-w64-mingw32-cxx11-julia_version+1.13.0.tar.gz"
