# Autogenerated wrapper script for blockSQP_mumps_jll for x86_64-apple-darwin-julia_version+1.10.0
export libblockSQP, libblockSQP_MUMPS, libblockSQP_MUMPS_wrapper, libblockSQP_wrapper

using libcxxwrap_julia_jll
using qpOASES_mumps_jll
JLLWrappers.@generate_wrapper_header("blockSQP_mumps")
JLLWrappers.@declare_library_product(libblockSQP, "@rpath/libblockSQP.dylib")
JLLWrappers.@declare_library_product(libblockSQP_MUMPS, "@rpath/libblockSQP_MUMPS.dylib")
JLLWrappers.@declare_library_product(libblockSQP_MUMPS_wrapper, "@rpath/libblockSQP_MUMPS_wrapper.dylib")
JLLWrappers.@declare_library_product(libblockSQP_wrapper, "@rpath/libblockSQP_wrapper.dylib")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll, qpOASES_mumps_jll)
    JLLWrappers.@init_library_product(
        libblockSQP,
        "lib/libblockSQP.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libblockSQP_MUMPS,
        "lib/libblockSQP_MUMPS.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libblockSQP_MUMPS_wrapper,
        "lib/libblockSQP_MUMPS_wrapper.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libblockSQP_wrapper,
        "lib/libblockSQP_wrapper.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
