# Autogenerated wrapper script for blockSQP_mumps_jll for x86_64-linux-gnu-cxx11-julia_version+1.11.1
export libblockSQP, libblockSQP_MUMPS, libblockSQP_MUMPS_wrapper, libblockSQP_wrapper

using libcxxwrap_julia_jll
using qpOASES_mumps_jll
JLLWrappers.@generate_wrapper_header("blockSQP_mumps")
JLLWrappers.@declare_library_product(libblockSQP, "libblockSQP.so")
JLLWrappers.@declare_library_product(libblockSQP_MUMPS, "libblockSQP_MUMPS.so")
JLLWrappers.@declare_library_product(libblockSQP_MUMPS_wrapper, "libblockSQP_MUMPS_wrapper.so")
JLLWrappers.@declare_library_product(libblockSQP_wrapper, "libblockSQP_wrapper.so")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll, qpOASES_mumps_jll)
    JLLWrappers.@init_library_product(
        libblockSQP,
        "lib/libblockSQP.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libblockSQP_MUMPS,
        "lib/libblockSQP_MUMPS.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libblockSQP_MUMPS_wrapper,
        "lib/libblockSQP_MUMPS_wrapper.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libblockSQP_wrapper,
        "lib/libblockSQP_wrapper.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
