# Autogenerated wrapper script for blockSQP_mumps_jll for x86_64-w64-mingw32-cxx11-julia_version+1.11.1
export libblockSQP, libblockSQP_MUMPS, libblockSQP_MUMPS_wrapper, libblockSQP_wrapper

using libcxxwrap_julia_jll
using qpOASES_mumps_jll
JLLWrappers.@generate_wrapper_header("blockSQP_mumps")
JLLWrappers.@declare_library_product(libblockSQP, "libblockSQP.dll")
JLLWrappers.@declare_library_product(libblockSQP_MUMPS, "libblockSQP_MUMPS.dll")
JLLWrappers.@declare_library_product(libblockSQP_MUMPS_wrapper, "libblockSQP_MUMPS_wrapper.dll")
JLLWrappers.@declare_library_product(libblockSQP_wrapper, "libblockSQP_wrapper.dll")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll, qpOASES_mumps_jll)
    JLLWrappers.@init_library_product(
        libblockSQP,
        "bin\\libblockSQP.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libblockSQP_MUMPS,
        "bin\\libblockSQP_MUMPS.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libblockSQP_MUMPS_wrapper,
        "bin\\libblockSQP_MUMPS_wrapper.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libblockSQP_wrapper,
        "bin\\libblockSQP_wrapper.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
